using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace LitIso.CharacterCreator
{
    /// <summary>
    /// Loads Resources/Characters/Layers/layer_catalog.json (v3) — the single
    /// source of truth for the paperdoll wardrobe. Generated by
    /// `Pixel Pipeline/character_forge/import_lpc.py` from the Universal LPC
    /// sheets (attribution: CREDITS_CHARACTERS.txt, also shipped at
    /// Resources/Characters/Layers/lpc_credits.txt for a credits screen).
    ///
    /// Sheet contract: every animation sheet is 8 rows (S,SE,E,NE,N,NW,W,SW,
    /// top->bottom) x <see cref="AnimationDef.cols"/> frames of frameSize px.
    /// Each item ships one sheet PER animation (see <see cref="animations"/>:
    /// walk, cast, thrust, slash, shoot, hurt — the "classic" 21-row LPC block
    /// that's present on every curated sheet, so every equipped layer covers
    /// every animation). "walk" doubles as idle (frame `idleFrame`) + the walk
    /// cycle (frames walkStartFrame..cols-1).
    /// Items can have multiple draw layers (e.g. capes: front + behind-body),
    /// each with its own sortOrder (LPC zPos). Resource templates contain
    /// {anim}, {body} and {variant} placeholders.
    /// </summary>
    [Serializable]
    public class DrawDef
    {
        public string template;
        public int sortOrder;

        public string Resolve(string animId, string bodyType, string variant) =>
            template.Replace("{anim}", animId).Replace("{body}", bodyType).Replace("{variant}", variant);
    }

    [Serializable]
    public class AnimationDef
    {
        public string id;          // walk|cast|thrust|slash|shoot|hurt
        public int cols;
        public int idleFrame;      // only meaningful for "walk"
        public int walkStartFrame; // only meaningful for "walk"
        public float fps;
    }

    [Serializable]
    public class ItemDef
    {
        public string id;            // e.g. "lpc/hair_afro"
        public string slot;          // body|head|eyes|hair|shirt|pants|shoes|accessory
        public string displayName;
        public bool matchBodyColor;  // variant follows the chosen skin tone
        public string[] variants;
        public DrawDef[] draws;

        public bool HasVariant(string v) => Array.IndexOf(variants, v) >= 0;

        public string SafeVariant(string v) =>
            variants.Length == 0 ? "" : (HasVariant(v) ? v : variants[0]);
    }

    [Serializable]
    public class CharacterLayerCatalog
    {
        public int version = 3;
        public int frameSize = 64;
        public int rows = 8;
        public string defaultAnimation = "walk";
        public AnimationDef[] animations;
        public float pixelsPerUnit = 50f;
        public float pivotX = 0.5f;
        public float pivotY = 0.5f;
        public string[] bodyTypes = { "male", "female" };
        public ItemDef[] items;

        public const string ResourcePath = "Characters/Layers/layer_catalog";
        public const string CreditsResourcePath = "Characters/Layers/lpc_credits";

        /// <summary>Animation definition by id, falling back to defaultAnimation.</summary>
        public AnimationDef Animation(string id)
        {
            if (animations == null || animations.Length == 0) return null;
            var found = animations.FirstOrDefault(a => a.id == id);
            return found ?? animations.FirstOrDefault(a => a.id == defaultAnimation) ?? animations[0];
        }

        public IEnumerable<string> AnimationIds => animations?.Select(a => a.id) ?? Enumerable.Empty<string>();

        static CharacterLayerCatalog s_Instance;

        public static CharacterLayerCatalog Instance
        {
            get
            {
                if (s_Instance == null)
                {
                    var txt = Resources.Load<TextAsset>(ResourcePath);
                    if (txt == null)
                    {
                        Debug.LogError($"[CharacterLayerCatalog] Missing Resources/{ResourcePath}.json");
                        s_Instance = new CharacterLayerCatalog { items = Array.Empty<ItemDef>() };
                    }
                    else
                    {
                        s_Instance = JsonUtility.FromJson<CharacterLayerCatalog>(txt.text);
                    }
                }
                return s_Instance;
            }
        }

        public static bool Available =>
            Resources.Load<TextAsset>(ResourcePath) != null && Instance.items.Length > 0;

        /// <summary>Credits text that must be reachable from the game (licenses).</summary>
        public static string CreditsText =>
            Resources.Load<TextAsset>(CreditsResourcePath)?.text ?? "";

        public ItemDef Find(string id) => items.FirstOrDefault(i => i.id == id);

        public List<ItemDef> Slot(string slot) => items.Where(i => i.slot == slot).ToList();

        public ItemDef First(string slot) => items.FirstOrDefault(i => i.slot == slot);
    }
}
