using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace IsoCore.Foundation.EditorTools
{
    /// <summary>Audit + reference-inventory report actions.</summary>
    public static class FoundationReports
    {
        static string ModuleDir => Path.Combine(Application.dataPath, "Scripts", "IsoCoreFoundation");

        public static string AuditProject(bool showDialog)
        {
            FoundationPaths.EnsureDocsDir();
            var c = FoundationContent.BuildDefault();

            int files = Directory.Exists(ModuleDir)
                ? Directory.GetFiles(ModuleDir, "*.cs", SearchOption.AllDirectories).Length : 0;

            var sb = new StringBuilder();
            sb.AppendLine("# ISO-Core Foundation — Project Audit");
            sb.AppendLine();
            sb.AppendLine($"> Generated by `Tools/LIT-ISO/ISO-Core Foundation/Audit Project`.");
            sb.AppendLine();
            sb.AppendLine($"- Module scripts (`Assets/Scripts/IsoCoreFoundation`): **{files}** .cs files");
            sb.AppendLine($"- Foundation scene present: **{File.Exists(Path.Combine(FoundationPaths.ProjectRoot, FoundationPaths.ScenePath))}**");
            sb.AppendLine();
            sb.AppendLine("## Content databases");
            sb.AppendLine();
            sb.AppendLine("| Database | Count |");
            sb.AppendLine("|---|---|");
            sb.AppendLine($"| Blocks | {c.Blocks.Count} |");
            sb.AppendLine($"| Block groups | {c.BlockGroups.Count} |");
            sb.AppendLine($"| Biomes | {c.Biomes.Count} |");
            sb.AppendLine($"| Items | {c.Items.Count} |");
            sb.AppendLine($"| Placeables | {c.Placeables.Count} |");
            sb.AppendLine($"| Recipes | {c.Recipes.Count} |");
            sb.AppendLine($"| Resource nodes | {c.Nodes.Count} |");
            sb.AppendLine($"| Mobs | {c.Mobs.Count} |");
            sb.AppendLine();
            sb.AppendLine("This module is an isolated assembly (`IsoCore.Foundation`) with no references to");
            sb.AppendLine("the legacy `Assembly-CSharp`. See Docs/IsoCoreFoundation/03_Foundation_Architecture.md.");

            File.WriteAllText(Path.Combine(FoundationPaths.DocsDir, "Foundation_Audit.md"), sb.ToString());
            AssetDatabase.Refresh();

            string log = $"[ISO-Core] Audit: {files} module scripts; content built " +
                         $"(blocks {c.Blocks.Count}, items {c.Items.Count}, recipes {c.Recipes.Count}). " +
                         "Report: Docs/IsoCoreFoundation/Foundation_Audit.md";
            if (showDialog) EditorUtility.DisplayDialog("ISO-Core Foundation — Audit", log, "OK");
            Debug.Log(log);
            return log;
        }

        public static string InventoryReference(bool showDialog)
        {
            string json = FoundationPaths.ReferenceInventoryJson;
            bool present = File.Exists(json);
            long size = present ? new FileInfo(json).Length : 0;

            string log = present
                ? $"[ISO-Core] ISO-CORE reference inventory present ({size / 1024} KB) at " +
                  "Docs/IsoCoreFoundation/iso_core_reference_inventory.json (+ .csv). " +
                  "Taxonomy: see 02_IsoCore_Reference_Study.md. Research-only — not wired into the scene."
                : "[ISO-Core] Reference inventory NOT found. It is produced by the WF1+WF2 research pass " +
                  "(catalog.json/DLL parse). Re-run that to regenerate Docs/IsoCoreFoundation/iso_core_reference_inventory.json.";

            if (showDialog) EditorUtility.DisplayDialog("ISO-Core Foundation — Reference Inventory", log, "OK");
            Debug.Log(log);
            return log;
        }
    }
}
