using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace LitIso.CharacterCreator
{
    /// <summary>
    /// Loads Resources/Characters/Layers/layer_catalog.json (v4) — the single
    /// source of truth for the paperdoll wardrobe. Generated by
    /// scripts/lpc_import.py from the Universal LPC sheets (attribution shipped at
    /// Resources/Characters/Layers/lpc_credits.txt for a credits screen).
    ///
    /// v4 model: one base sheet per (item x bodyType), sliced + recolored at
    /// runtime by CharacterCompositor. Source art is 4-directional
    /// (rowOrder = N,W,S,E); E is mirrored from W and diagonals snap to the
    /// nearest cardinal at runtime. Row layout is per-item (AnimationDef holds
    /// rowOffset/rows/cols/fps for every animation the item ships).
    /// See Docs/design/LPC_IMPORT_PIPELINE.md.
    /// </summary>
    [Serializable]
    public class DrawDef
    {
        public string bodyType;   // male|female
        public string sheet;      // Resources path of the base sheet (no .png.bytes suffix)
        public int sortOrder;     // LPC zPos
    }

    [Serializable]
    public class AnimationDef
    {
        public string id;         // walk|spellcast|thrust|slash|shoot|hurt|idle|...
        public int rowOffset;     // band top, in 64px sheet rows
        public int rows;          // 4 (cardinal) or 1 (hurt/climb)
        public int cols;          // frames per row
        public float fps;

        // Oversize swing bands (great weapons / tools). When frameSize > 0 the
        // band is authored at frameSize px (128 or 192), the body (64px) is
        // centred inside it (frameOffset = (frameSize-64)/2), and rowOffsetPx is
        // the exact pixel offset of the band's top from the sheet top (because
        // rowOffset in 64px-row units cannot address a 192px-row band). Default 0
        // = a normal 64px band (use the catalog frameSize / rowOffset*64).
        public int frameSize;     // 0 => normal (catalog frameSize, 64)
        public int frameOffset;   // px the 64px body is inset within an oversize frame
        public int rowOffsetPx;   // exact pixel offset of band top from sheet top

        public bool IsOversize => frameSize > 64;
        /// <summary>Effective frame size of this band's source rows.</summary>
        public int FrameSizeOr(int fallback) => frameSize > 0 ? frameSize : fallback;
        /// <summary>Pixel offset of the band top from sheet top.</summary>
        public int TopPx(int fallbackFrame) => frameSize > 0 ? rowOffsetPx : rowOffset * fallbackFrame;
    }

    [Serializable]
    public class ItemDef
    {
        public string id;            // e.g. "lpc/hair_bangs"
        public string slot;          // body|head|eyes|hair|shirt|pants|shoes|weapon|offhand|hands|accessory
        public string kind;          // cosmetic|equipment
        public string equipSlot;     // equipment only: weapon|offhand|head|chest|legs|feet|hands|shoulders|back|waist|accessory
        public string displayName;
        public bool matchBodyColor;  // variant follows the chosen skin tone
        public string paletteMaterial; // body|cloth|metal|hair|eye|null
        public string baseVariant;   // the variant the stored sheet is authored in (source ramp)
        public string[] variants;
        public AnimationDef[] animations;
        public DrawDef[] draws;

        public bool creatorExcluded;  // true = missing core animations; hide from creator UI

        public bool IsEquipment => kind == "equipment";
        public bool IsCosmetic => kind == "cosmetic";
        public bool IsCreatorVisible => IsCosmetic && !creatorExcluded;

        public bool HasVariant(string v) => variants != null && Array.IndexOf(variants, v) >= 0;

        public string SafeVariant(string v) =>
            (variants == null || variants.Length == 0) ? "" : (HasVariant(v) ? v : variants[0]);

        /// <summary>This item's layout for one animation, or null if it doesn't ship it.</summary>
        public AnimationDef Anim(string id)
        {
            if (animations == null) return null;
            for (int i = 0; i < animations.Length; i++)
                if (animations[i].id == id) return animations[i];
            return null;
        }

        /// <summary>Base sheet path for a bodyType, or "" if this item has none.</summary>
        public string SheetFor(string bodyType)
        {
            if (draws == null) return "";
            for (int i = 0; i < draws.Length; i++)
                if (draws[i].bodyType == bodyType) return draws[i].sheet;
            // fall back to any draw (some items ship a single unisex body)
            return draws.Length > 0 ? draws[0].sheet : "";
        }

        public DrawDef DrawFor(string bodyType)
        {
            if (draws == null) return null;
            for (int i = 0; i < draws.Length; i++)
                if (draws[i].bodyType == bodyType) return draws[i];
            return draws.Length > 0 ? draws[0] : null;
        }
    }

    [Serializable]
    public class CharacterLayerCatalog
    {
        public int version = 4;
        public int frameSize = 64;
        public string defaultAnimation = "walk";
        public string[] rowOrder = { "N", "W", "S", "E" };
        public float pixelsPerUnit = 64f;
        public float pivotX = 0.5f;
        public float pivotY = 0.5f;
        public string[] bodyTypes = { "male", "female" };
        public ItemDef[] items;

        public const string ResourcePath = "Characters/Layers/layer_catalog";
        public const string CreditsResourcePath = "Characters/Layers/lpc_credits";

        /// <summary>Direction index for a rowOrder code (N/W/S/E), or -1.</summary>
        public int RowIndex(string code)
        {
            if (rowOrder == null) return -1;
            for (int i = 0; i < rowOrder.Length; i++)
                if (rowOrder[i] == code) return i;
            return -1;
        }

        /// <summary>
        /// Distinct animation ids present across the catalog (driven by the body
        /// item, which ships every animation). Used by the creator's anim cycler.
        /// </summary>
        public IEnumerable<string> AnimationIds
        {
            get
            {
                var body = Find("lpc/body") ?? items?.FirstOrDefault(i => i.slot == "body");
                if (body?.animations != null && body.animations.Length > 0)
                    return body.animations.Select(a => a.id);
                return new[] { defaultAnimation };
            }
        }

        static CharacterLayerCatalog s_Instance;

        public static CharacterLayerCatalog Instance
        {
            get
            {
                if (s_Instance == null)
                {
                    var txt = Resources.Load<TextAsset>(ResourcePath);
                    if (txt == null)
                    {
                        Debug.LogError($"[CharacterLayerCatalog] Missing Resources/{ResourcePath}.json");
                        s_Instance = new CharacterLayerCatalog { items = Array.Empty<ItemDef>() };
                    }
                    else
                    {
                        s_Instance = JsonUtility.FromJson<CharacterLayerCatalog>(txt.text);
                    }
                }
                return s_Instance;
            }
        }

        public static bool Available =>
            Resources.Load<TextAsset>(ResourcePath) != null && Instance.items.Length > 0;

        public static string CreditsText =>
            Resources.Load<TextAsset>(CreditsResourcePath)?.text ?? "";

        public ItemDef Find(string id) =>
            string.IsNullOrEmpty(id) ? null : items.FirstOrDefault(i => i.id == id);

        public List<ItemDef> Slot(string slot) => items.Where(i => i.slot == slot).ToList();

        /// <summary>Items in a slot that the creator may offer (cosmetic, full animation coverage).</summary>
        public List<ItemDef> CosmeticSlot(string slot) =>
            items.Where(i => i.slot == slot && i.IsCreatorVisible).ToList();

        public ItemDef First(string slot) => items.FirstOrDefault(i => i.slot == slot);

        public ItemDef FirstCosmetic(string slot) =>
            items.FirstOrDefault(i => i.slot == slot && i.IsCreatorVisible);

        /// <summary>Non-base body cosmetics (tails, wings) layerable over the body.</summary>
        public List<ItemDef> BodyExtras() =>
            items.Where(i => i.slot == "body" && i.IsCreatorVisible && i.id != "lpc/body").ToList();

        /// <summary>Head accessory cosmetics (ears, horns, fins, etc.).</summary>
        public List<ItemDef> HeadExtras() => CosmeticSlot("head");
    }
}
